### ISSUE TITLE
Global overview

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#1]
Monterey is an extensible application that provides a graphical user interface for a collection of tools to simplify the creation, configuration and maintenance of Aurelia applications.

When monterey is opened for the first time, an aurelia project can be scaffolded or opened:
![image](https://cloud.githubusercontent.com/assets/2189477/16310777/368f643c-396e-11e6-828b-cdcac170eb09.png)

As soon as a single project has been added to monterey, the following screen is the home screen for monterey:
![image](https://cloud.githubusercontent.com/assets/2189477/16308493/763f33d6-3965-11e6-9258-63aaac206a2b.png)

Plugins have a dedicated area of the monterey screen to show their UI in:
![image](https://cloud.githubusercontent.com/assets/2189477/16308636/17fc6b1c-3966-11e6-9aab-3b5e5a30df98.png)

The idea is to keep the monterey-framework clean and to keep most of the logic in plugins. That way the focus of monterey-framework is put on the plugin infrastructure, and it becomes possible for users to create their own plugins. These plugins can then be just as powerful as "native" plugins that we will create initially

**Comment by vegarringdal** [comment]
Been thinking about this for a while

In our interface we want our users to have list of their projects added to Monterey.
What about instead of doing a dialog first time we do something like this :[overlay info](http://stackoverflow.com/questions/10216937/how-do-i-create-a-help-overlay-like-you-see-in-a-few-android-apps-and-ics) then the app is first started ?

Overlays like this can be annoying if you have seen it before, so it will be important to have a option to skip right away if we have more then 1 page explaining the usage of the application.

**Comment by adriatic** [comment]
I @vegarringdal writes
> In our interface we want our users to have list of their projects added to Monterey.
What about instead of doing a dialog first time we do something like this :overlay info then the app is first started ?

This is something that is a lot better implement the "classic" way (as all desktop applications do) - have a per user (persistent) record of all settings relevant to user's preferences, that start with the application window size and position, list of recent projects, ...

**Comment by JeroenVinke** [comment]
this issue no longer has any use
