### ISSUE TITLE
Closing Monterey app still does not exit the gulp watch command

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#160]
![image](https://cloud.githubusercontent.com/assets/2712405/17717592/e6b3928c-63dc-11e6-90dc-7908e72f4a39.png)

**Comment by JeroenVinke** [comment]
@vegarringdal Yesterday I tried to implement https://github.com/Quramy/electron-connect/issues/2#issuecomment-126706085 (again, since it stopped working somehow) and I can't get it to work. `client.sendMessage('closed');` is executed but not received via `electron.on('closed')`. Can you take a stab at this?

**Comment by vegarringdal** [comment]
Sure Ill have a look at it, dunno when I get a chance, but then I have a task to do when I get time :-)
Will be online, for 1 hours now, maybe I get lucky :-)

**Comment by JeroenVinke** [comment]
I wish you good luck :smile:

**Comment by JeroenVinke** [comment]
Just tried to fix it again but still doesn't work. It would be unsensible to put more hours into this
