### ISSUE TITLE
How will Monterey auto update work?

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#185]
The very first question from Rob after I mentioned new Monterey was: will you have the auto-update feature. So, this is clearly something we need to pay a lot of attention to and I want to share the latest Visual Studio 2015 UI solution for this:

![image](https://cloud.githubusercontent.com/assets/2712405/17819325/5a00d1c0-6615-11e6-8a6c-7fd79c37a1d0.png)

**Comment by JeroenVinke** [comment]
Right now it works like [this](https://github.com/monterey-framework/monterey/issues/115#issuecomment-240094290). How do you propose to use the visual studio way of updates in monterey, based on what we already have

**Comment by adriatic** [comment]
I believe that what Visual Studio has built in is a "little subscription service" written to listen to the "publish server" running by MS team. So, they provide the updates to VS on a well known location and "push" the notification to all VS users.

If this is not the way VS notifications work, it is certainly something we can build for Monterey without a major effort. Being able to "know" all our subscribers is certainly a plus for us - as it is the registered based of customers that counts a lot in other folks assessing the value of our "software factory" - and we better start with this right away; it would be a lot harder to request Monterey users to register their products once the barn door is already opened. 

Let me know how you like this idea, please.

**Comment by JeroenVinke** [comment]
I think this may fall outside the updater category, but still something to think about. It would be great to have an overview of all monterey users, and it would be handy if we could reach them (say via an email address they registered). But I do not want to scare people away where they think that going through the registration process is not worth it.

And if we are going to have accounts then we need some place to register the accounts (the monterey service/api).

I would prefer to launch without users needing an account, as it will take time to design and build it so that it is a feature and not a hassle.

As for the updater, as soon as we create a release on github and the user starts monterey it will download the update and notify the user that it gets installed upon restart

**Comment by adriatic** [comment]
> As for the updater, as soon as we create a release on github and the user starts monterey it will download the update and notify the user that it gets installed upon restart

I missed this reading your description of the update process as it now; as long as we push (instead of having to wait for the user to discover somehow that the update exists and make a pull) I am fine.

Sometimes I do hate this infinite drive to be free - when having to register something makes people run away.

**Comment by JeroenVinke** [comment]
> as long as we push (instead of having to wait for the user to discover somehow that the update exists and make a pull) I am fine.

:+1:
