### ISSUE TITLE
Default ESNext - Au Run --watch fails

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#195]
![image](https://cloud.githubusercontent.com/assets/2712405/17946157/212f2604-6a15-11e6-900b-1ac4a3691d12.png)

<br>

![image](https://cloud.githubusercontent.com/assets/2712405/17946175/33d66344-6a15-11e6-914c-b54d1c3db0fe.png)

<br>

![image](https://cloud.githubusercontent.com/assets/2712405/17946191/4690d190-6a15-11e6-9d90-d324d31b4018.png)

<br>

![image](https://cloud.githubusercontent.com/assets/2712405/17946203/565e45e4-6a15-11e6-8bb9-a37893d28ec5.png)

**Comment by JeroenVinke** [comment]
Interesting, "Default ESNext" seems to be an invalid name for a npm package (it contains a space). The project name is put in package.json in the name field. I think this caused npm install to fail.

The output from "Au run --watch" is what you get when the node modules of an aurelia cli app are not installed. Not sure if this is caused by the invalid name though

**Comment by adriatic** [comment]
You should expect that I will always find interesting cases. I will restrict myself now to not use any spaces and we can test a fix for that separately.

At the moment, I want to "drive" as deep into these tests as I can go, keeping the [template](https://github.com/monterey-framework/monterey/issues/194)
