### ISSUE TITLE
Clearing cache gives error on linux

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#203]
![image](https://cloud.githubusercontent.com/assets/2189477/17965210/b5859ddc-6abb-11e6-9626-77ee845b2b12.png)

**Comment by vegarringdal** [comment]
vmware image

**Comment by JeroenVinke** [comment]
The screenshot is from @vegarringdal

**Comment by JeroenVinke** [comment]
@vegarringdal would you mind taking a look at this? you seem to have linux up and running :smile:

**Comment by vegarringdal** [comment]
Ill try and push it inn between stuff :-) 
Not much spare time lately

**Comment by vegarringdal** [comment]
Did a test on this, my first issue with monterey not starting got solved by disabling this
https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/index.ts#L2
After I created 1 project and enabled the line I was not having loading issues again...

Clear cache still gives error, need to look more into that one

**Comment by vegarringdal** [comment]
I dont have any git tools here, so here is what I found out on my vmware image

This need to be edited:

**The part that broke the loading of app**
https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/app-launcher/index.ts#L57

```javascript
let launchers = (<any>defaults).defaults[platform] || [];
```
Else the ```foreach``` after will break it since launchers are undefined

**What I did to fix clear cache**
https://github.com/monterey-framework/monterey/blob/master/app/index.js#L138
```javascript
mainWindow.loadURL(getIndex());
```

this ```BrowserWindow.getFocusedWindow()``` returns null...
from what I can see the confirm dialog takes it away, but using the ```mainWindow``` is just as safe since app is closed if we done have it..

**Comment by vegarringdal** [comment]
just need to make sure this dont mess up windows/mac, but cant really see how any of these edits would do so

**Comment by JeroenVinke** [comment]
Nice :+1: will implemen the fixes tomorrow
