### ISSUE TITLE
Monterey leaving running apps running

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#210]
***Note: I think that not being able to shut down Electron on Monterey exist is still an open issue, so I want to share another view of this problem.***

I just observed that the task `au run --watch` which I created several hours back and which led me to the https://github.com/monterey-framework/monterey/issues/209  is still running - despite me killing the `gulp watch`, rebuilding Monterey with the fix for #209 and then (using the Task Manager) invoked `au-run --watch`, which resulted with the app running at port 9001.

Having live Monterey, I was able to end the `au-run --watch` listening at 9001 - but the listener at 9000 is happily responding.

Here is what Windows Task Manager "sees":

![image](https://cloud.githubusercontent.com/assets/2712405/17982499/0159bda0-6ad6-11e6-99bd-5ded12fd7aac.png)

**Comment by JeroenVinke** [comment]
This could very well be the case, as killing `gulp watch` forces monterey to quit, while exiting monterey via via the X button will execute kill all running child processes. So as long as monterey is exited "safely" then this should be no problem. Maybe we can solve this issue in development though. 

The two electron processes may not be zombie processes, as electron-remote spins up these instances in order to asynchronously do heavy tasks, such as `npm install`

**Comment by adriatic** [comment]
> The two electron processes may not be zombie processes

You are right: I tried to kill "zombies" with Windows Task Manager and the running instance (the one showing Monterey as a child) died as well.

**Comment by JeroenVinke** [comment]
I don't think we can fix this. If you terminate `gulp watch` then electron gets quit ungracefully and it has no time to kill running tasks. Users will quit the app gracefully at which point [this gets executed](https://github.com/monterey-framework/monterey/blob/master/app/src/cleanup.ts#L14-L16).
