### ISSUE TITLE
Create typings plugin

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#227]
https://github.com/typings/typings

if a project has a `typings.json` file, then the typings must be installed via `typings install`. There should be an action at the end of the scaffolding wizard that allows you to install the typings. Not sure if we should go all out on creating a GUI for the typings tool, because of [this blog post](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)

**Comment by adriatic** [comment]
> Not sure if we should go all out on creating a GUI for the typings tool, because of [this blog post](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)

I am strongly in favor of doing the maximum we can in this area - as having to deal with Monterey support in the area Monterey should shine (make complex installation tasks easy) is really stupid :smile:

**Comment by JeroenVinke** [comment]
Just to confirm we read the article the same, the typings tool will soon be unnecessary. Monterey should be able to install typings automatically (this is easy), but a complete typings management screen to add/remove typings is not worth our time since the typings tool may not be around that long

**Comment by adriatic** [comment]
When you wrote `Not sure if we should go all out on creating a GUI for the typings tool` - I understood it as your intent to **go all out** - where your idea was **not to go all out** because of the pending automation. 

My drift was meant to ensure that we do the best we can do now - as I was completely confused by not being able to build the Typescript app with Monterey and assumed immediately that others will be confused as well. I am still confused why is it that so deep in the Typescript "era" one has to do some "post-install" actions.

**Comment by JeroenVinke** [comment]
> When you wrote Not sure if we should go all out on creating a GUI for the typings tool - I understood it as your intent to go all out - where your idea was not to go all out because of the pending automation.

Ah yes, darn words
