### ISSUE TITLE
What is the planned functionality for initial release:

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#233]
### Today's status

I have created applications using all currently supported templates:

![image](https://cloud.githubusercontent.com/assets/2712405/18034237/ac5fdaa0-6d05-11e6-8a26-5545cb0e2821.png)

and expect to be able to run them all today ( the asp.net based ones are not fully supported by Monterey and I want to find out what is missing to run them directly).

We still need to clearly define the planned functionality for the NPM and JSPM tiles. At the moment, they offer 

**`NPM tile`**: `Install`, `Update selected` and `Refresh`

**`JSPM tile`** : `Update all`, `Update selected` and `Refresh`

Both tools use v-grid with same columns: `Installed version`, `Range` and `Latest`

These tiles are described in the **[Monterey overview](https://aurelia-ui-toolkits.gitbooks.io/monterey-overview/content/)** manual, **[Monterey tiles](https://aurelia-ui-toolkits.gitbooks.io/monterey-overview/content/monterey_tiles.html)** chapter (which now incorrectly shows the jspm section)

### Final status for this release

As I was not involved in the planning for some tiles (npm, jspm in particular), I suggest that @JeroenVinke verifies the **[Monterey overview](https://aurelia-ui-toolkits.gitbooks.io/monterey-overview/content/)** manual to check for accuracy (are we documenting all that is functional, are we missing to document something that is functional)

**Comment by adriatic** [comment]
Based on verification that I am proposing @JeroenVinke to do, I will then whip up the **[Managing existing applications](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/managing_existing_application.html)** chapter. This will be more a set of promises for the subsequent releases than the description of how to use what is available today.

**Comment by JeroenVinke** [comment]
> and expect to be able to run them all today ( the asp.net based ones are not fully supported by Monterey and I want to find out what is missing to run them directly).

That is what https://github.com/monterey-framework/monterey/issues/227 and https://github.com/monterey-framework/monterey/issues/225 will resolve.

> We still need to clearly define the planned functionality for the NPM and JSPM tiles. At the moment, they offer

Based on Robs initial feedback I'd say we have plenty of features for an initial release. https://github.com/monterey-framework/monterey/issues/227 and https://github.com/monterey-framework/monterey/issues/225 will introduce two new tiles (typings and dotnet) but the screens behind these tiles will contain only placeholders, as monterey just needs to detect Typings and DotNet projects, so that Monterey can scaffold and install the dotnet+typescript projects correctly. Basically, Monterey needs to detect the project.json file so it can run `dotnet restore` and `dotnet run`.

I will update https://aurelia-ui-toolkits.gitbooks.io/monterey-overview/content/ and let you know when it is finished

**Comment by adriatic** [comment]
# :+1:
