### ISSUE TITLE
Projects with running tasks should be above projects without running tasks

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#264]
![image](https://cloud.githubusercontent.com/assets/2189477/18210984/928e83d0-713b-11e6-846b-9bf5c6fa650a.png)

**Comment by adriatic** [comment]
I feel sometimes that this grid view is too crowded, so highlighting the running task(s) is my best navigation help here. 

How about setting `show finished tasks` false by default (as I am still not sure why would I need to see the more than a proof of a successful execution of the `end task` command. Once I see that, since i cannot restart them (not to say that can find the need for such activation) I would like to remove them completely.

**Comment by adriatic** [comment]
As the projects are added according to `add below last` rule, I am not sure that any sorting action done by Monterey would be of value. 

If the list of projects is at the order of 10+ - we would need to offer alphabetical and `last accessed` time as criteria - just as I always to with Files Explorer. To mimic the "real"  Task manager we should also consider sorting by `running time` and eventually by `resources usage` when we get the access to basic OS API.

**Comment by JeroenVinke** [comment]
Continuing in https://github.com/monterey-framework/monterey/issues/287
