### ISSUE TITLE
Improving Monterey project creation and management

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#277]
This task would be better defined once we hear more from Rob as its implementation would certainly be better with the help from Aurelia-CLI. 

***

### Summary 
This proposal discusses the further advancement of Monterey - from being the application "generator" to become application "maintainer" tool.

***

### Introduction
Aurelia-CLI is really no different from Aurelia Navigation Skeletons in the sense that it helps you to **create** the skeleton of your app - either via the wizard defining the project's content (CLI) or by choosing the specific skeleton (Aurelia Navigation Skeletons collection). Once the project is **created**, the user **is on his own** except for Aurelia-CLI additional information given as instructions to the user:

- [Adding Client Libraries to Your Project](https://github.com/aurelia/cli#adding-client-libraries-to-your-project)
  - [A Single-File Module](https://github.com/aurelia/cli#a-single-file-module)
  - [A CommonJS Package](https://github.com/aurelia/cli#a-commonjs-package)
  - [A Legacy Library](https://github.com/aurelia/cli#a-legacy-library)
  - [A Library with Additional Resources](https://github.com/aurelia/cli#a-library-with-additional-resources)
  - [A Very Stubborn Legacy Library](https://github.com/aurelia/cli#a-very-stubborn-legacy-library)

All these instructions are really instructions on how to use RequireJS module loader and are made relevant in this context, because Aurelia-CLI supports only RequireJS (at least for now).

Monterey app created by using Aurelia-CLI method, uses this information on the "Monterey workflow page" shown below

![image](https://cloud.githubusercontent.com/assets/2712405/18253095/10b2f112-7360-11e6-9be1-55e8fb5fc8e9.png)

where the user has the ability to activate proposed tasks, which will result with the app being built and run.

This same "Monterey workflow page" could be a bit more complex (as discussed **[here](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application/skeleton-typescript-aspnetcore.html))**

![image](https://cloud.githubusercontent.com/assets/2712405/18253210/e5cb1f3c-7360-11e6-9a46-780084edff3d.png)

because the app environment is more involved.

These few examples show how Monterey, regardless of whether using Aurelia-CLI or some fixed Skeleton to **define** the app, presents the application building process in a way where the user can interact with its definition **before** build is triggered. In other words, Monterey **extends** the interactivity provided by Aurelia-CLI, regardless of the way the app structure is initially defined. 

***

**Comment by adriatic** [comment]
### Proposal

As the next obvious steps in Monterey's evolution we should define **additional means to extend the application creation process**  and **initial means to implement application extensions**. Note that these are two completely different tasks:

1. **Extending application creation** means to extend the types of applications Monterey can generate.

2. **Adding initial means to extend an already generated applications** means to teach Monterey how to use different module loaders, add and remove third party libraries, etc.

### Extending application creation 

This could be infinitely big task, but luckily we have an area of recognition already - KendoUI Bridge with more than 17,000 downloads, which we need to nurture. So, extending Monterey to fully support the KendoUI bridge installation, covering all possible cases on this screenshot

![image](https://cloud.githubusercontent.com/assets/2712405/18256174/dec506b6-737f-11e6-9843-b6acea391a0b.png)

will result with tenfold increase of (both Monterey and KendoUI bridge) downloads. 

___to be continued___

**Comment by JeroenVinke** [comment]
> Extending application creation means to extend the types of applications Monterey can generate.

We came to the conclusion that this is necessary because the following is difficult to do:

> Adding initial means to extend an already generated applications means to teach Monterey how to use different module loaders, **add and remove third party libraries**, etc.

This is extremely difficult / impossible when you want to support all tech (aurelia-cli, jspm and webpack), as there is no standard at all 

I see many people switching from jspm/webpack to aurelia-cli, so if this trend continues then it will probably not be worth it to build something like this for jspm/webpack. We could just focus on aurelia-cli, and the good news is that @kristianmandrup has done this already. 

So my proposal would be to focus on aurelia-cli first, where we provide a great GUI for @kristianmandrup's [ai-plugin](https://github.com/kristianmandrup/ai-plugin). I have not read all documentation, but this would be the new workflow:

1. you create a new aurelia-cli project via monterey (no "link" to aurelia-kendoui-bridge)
2. you decide to add a new plugin (aurelia-kendoui-bridge) and use the Monterey GUI for `ai-plugin`.
3. the bridge knows how it should be installed, and instructs `ai-plugin` to do it

I'd rather do this even though it may take weeks to perfect, because this solve the problem for **all plugins** and not just our own

**Comment by adriatic** [comment]
> I see many people switching from jspm/webpack to aurelia-cli, so if this trend continues then it will probably not be worth it to build something like this for jspm/webpack. 

I agree completely - and have stated the same already (calling "support for Aurelia-CLI" as "support for RequireJS"). Using RequireJS as the module loader is the key property of Aurelia-CLI and I would rather use that term. So, take all of my recent writings about extending Monterey as extending Monterey while supporting RequireJS module loader only.

I was not fully aware of  the relevance of [ai-plugin](https://github.com/kristianmandrup/ai-plugin) in this context (and still do not) so I need to learn and understand that before being able to make further comments about the (lack of) meaningfulness to support jspm. In my own perception, jspm is clear and well documented module loader and I cannot say the same for RequireJS. As aurelia core team went the RequireJS way, I ought to be missing something.

**Comment by Thanood** [comment]
> I ought to be missing something.

I think the only thing you did miss is that requirejs has been there for (internet scale) ages and is very mature. While jspm/systemjs (is not because) in the past either broke the current Aurelia structure/workflow or introduced serious perfomance issues in Internet Explorer.

I don't like it, either.. Feels like a knee-jerk reaction to me. ("they broke my stuff, let's get something else")
Last year or so the Aurelia team was cooperating with Guy to fix issues rather than introduce another loader.

**Comment by JeroenVinke** [comment]
> I was not fully aware of the relevance of ai-plugin in this context (and still do not)

I'll give you the overview. ai-plugin takes care of the installation of plugins in an aurelia-cli project (not sure how things will hold when aurelia-cli is going to support jspm/webpack). If you execute `ai-plugin install dialog` then ai-plugin will install the aurelia-dialog plugin for you in your project. Plugins can provide pre- and post installation steps to ai-plugin, because only the plugin itself knows how it should be installed. If we configure aurelia-kendoui-bridge to work with ai-plugin, then users can install the bridge via `ai plugin install aurelia-kendoui-bridge`. Note that I have not tried this yet, but we can collaborate with the author of ai-plugin to get this working.

Now, Monterey can show a list of plugins that are supported by `ai-plugin`. The user would be able to select the plugin that he/she needs to install, and Monterey will execute the `ai-dialog install <plugin>` command for the user.

**Comment by AlainBaslter** [comment]
On the requirejs aspect. I have a constraint that is only applicable to me and perhaps a few others?
The app I am building uses ESRI JS API which depends on DOJO and the AMD loader variant that is embedded within. I use that AMD loader configured to load up Aurelia bundled and so far so good. That is why it is a good thing that aurelia-cli is requirejs i.e. AMD. I am currently working on making it load using vanilla requirejs instead of the DOJO AMD loader. 
I was looking at the code generated under aurelia-syncfusion-bridge under /dist/amd and see that they are AMD modules each in separate folders. To make the bridge work in my context I think I might need to use r.js to bundle it using some "main.js" entry point that define(["ejXX", "ejYY"]) so r.js can trace dependencies for the bundle. I don't quite know how to do that just yet but I am successfully  doing that for Aurelia. That is where an aurelia-syncfusion-bridge UI "Manager" in Monterey could generate those dependencies based on controls I choose to include.

**Comment by JeroenVinke** [comment]
Created https://github.com/monterey-framework/monterey/issues/281 for this

**Comment by adriatic** [comment]
@Thanood 
> I think the only thing you did "miss" is that requirejs has been there for (internet scale) ages and is very mature

I did not miss that - as I had a similar discussion with Rob, trying to push jspm as one of the supported module loaders. He ensured that I get well aware of RequireJS being the oldest and most stable module loader. At that time, I was tempted to ask why is it then that it appeared only in the latest Aurelia's methodology that provides app skeletons (Aurelia-CLI) - and it still does not exist in any of the Aurelia Navigation Skeletons. I quickly decided that such question is better to keep to myself :-)

From the viewpoint of the application developer, the choice of the module loader should be completely irrelevant as long as there is an easy to use method to set the loader up. We achieved that with jspm 016.x and if I would have to use this setup for the rest of the eternity, I would not care at all. 

As it is somewhat unlikely that we are creating Monterey solely for my use, my view of jspm does not carry much weight and I am completely on board with @JeroenVinke's preference to restrict Monterey to support only RequireJS - as long as we do not call this "supporting Aurelia-CLI". Just because you see a building with the big board on the roof spelling "Hotel", that does not imply that all buildings are hotels :smile:

**Comment by JeroenVinke** [comment]
The other side of the same coin is that we do not support "plain" requirejs either, we worm witv aurelia-cli. So aurelia-cli with the requirejs module loader would seem the best way to call it IMO

**Comment by adriatic** [comment]
I see no sense in continuing this discussion - Monterey will be extended using Aurelia-CLI only and I will pretend not to know that this means Monterey will support only RequireJS in the context of supporting Aurelia application maintenance.

**Comment by JeroenVinke** [comment]
Ok
