### ISSUE TITLE
add gistrun tile to monterey

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#43]
This will allow us a very cool twist: "direct" creation of problem reports with configurable destination (for these reports)

**Comment by JeroenVinke** [comment]
Added a gistrun tile which opens [this gist.run](https://gist.run/?id=14ac85668b3ca27dcd8ad6d3f6579fb0) in a browser when clicked. I don't think we should implement the feature that you're describing right now because it would take a lot of time to get it right, and we need to get the first release out as soon as we can

![image](https://cloud.githubusercontent.com/assets/2189477/16685055/c88820c2-4508-11e6-8bb2-1fa17620212d.png)

**Comment by adriatic** [comment]
> we need to get the first release out as soon as we can

1. I agree with your reasoning
2. Even if I don't - this is your call
3. At some point, in the distant future, I will do it if nobody else gets to it first :-)

**Comment by JeroenVinke** [comment]
closing in favor of https://github.com/monterey-framework/monterey/issues/75
