### ISSUE TITLE
custom jspm registries are not working in monterey

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#73]
![image](https://cloud.githubusercontent.com/assets/2189477/16878464/f4ace15c-4aac-11e6-84ee-3b94a35035c6.png)

this is with a project that uses jspm-git to download Kendo. JSPM tries to load `node_modules/jspm-git/package.json` but that doesn't exist in Monterey's node_modules, that only exists in the project's node_modules. This happens [here](https://github.com/jspm/jspm-cli/blob/master/lib/registry.js#L69)

**Comment by JeroenVinke** [comment]
The cleanest way would be to use jspm out of the node modules of the project (and not of monterey). But then we need to add a check so that npm install has been run before the jspm plugin can do anything, as otherwise there is no jspm folder in the node modules folder of the project

**Comment by adriatic** [comment]
I agree with 

> But then we need to add a check so that npm install has been run before the jspm plugin can do anything.

My gut feel is that the use of monterey should be "scripted" (and I am writing more about it in **[THE book](https://www.gitbook.com/book/aurelia-ui-toolkits/monterey-overview/details)**

For the purpose of this discussion I would argue the following view: 

In general, it makes no sense to click on the various tiles(see image below)  in a random fashion - instead, the user needs to know what is happening as a consequence of any click and what sequences of clicks do make sense and result with expected outcomes. This situation is no different from the outcome caused by a car driver that has never used manual speed shifting - and can shift from the fourth gear into "reverse". So we should at simplest maintain the monterey's state for each user and allow only "meaningful clicks"

A lot more user friendly version my be very close to a system administrator's heart, where he has the support for programming a workflow that "engages clicks on tiles" (do not take this metaphor to literally, please :-)

For the sake of this discussion I would ask: when does it not make sense to automatically invoke npm after all user selections are done?

![image](https://cloud.githubusercontent.com/assets/2712405/16880774/e2175356-4a84-11e6-9b76-edb67c159107.png)

**Comment by Thanood** [comment]
For example when the user wants to tweak package.json before running npm install (and thus spending minutes not being able to edit it). I do this regularly with skeletons, especially when testing webpack with materialize bridge. :smile: 

But imho NPM could be the only tile activated (the rest greyed out, but visible) until `npm install` is run (the directory `node_modules` is present).
